apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: time display app
  annotations:
    github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
